#third document in python generaring a conflit error